### ISSUE TITLE
brcm 40183 patch applied every time

### ISSUE THREAD

**Issue by kousha-icracked** [kdeenkhoorn/cubietruck-scripts#1]
Is there a reason why this patch needs to be applied every time on boot up? Why can't it be applied once only?

**Comment by kdeenkhoorn** [comment]
Sorry for my late reply, did not expect that this solution would be picked up so  did not check to often for issues .... ;-)

Just like a lot of devices at initialisation time of the hardware some firmware has to be loaded befor it can be used. Usually  this is done bij the kernel at boot time with data provided by the kernel firmware package.
This chipset is as up to the moment of writing not supported by the kenel yet. Therefor this upload of the firmware has to be done 'by hand' or script

It is important that this firmware upload has to be done before any process has touched the hardware, so before the bluetooth software is started.
This can be done by systemctl dependencies or sysvinit ordering.

The supplied script will do it for you and it has not failed me yet.
